# Generated by Django 2.1.5 on 2019-07-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
